#!/usr/bin/env bash
# Publish the generated static store (web/) to GitHub Pages.
# Usage: bash deploy.sh [repo-name]   (default: creator-store)
# Re-run after each `제작` to update the live site. Only web/ is published —
# secrets (.runmoa.json/.ai.json/.search.json) live outside web/ and never ship.
set -e
REPO="${1:-creator-store}"
OWNER="$(gh api user --jq .login)"
ROOT="$(cd "$(dirname "$0")" && pwd)"
DEPLOY="$ROOT/.deploy"

echo "▶ packaging web/ → .deploy"
rm -rf "$DEPLOY"; mkdir -p "$DEPLOY"
cp -R "$ROOT/web/." "$DEPLOY/"
touch "$DEPLOY/.nojekyll"            # serve files as-is (no Jekyll processing)

if ! gh repo view "$OWNER/$REPO" >/dev/null 2>&1; then
  echo "▶ creating public repo $OWNER/$REPO"
  gh repo create "$OWNER/$REPO" --public --description "Creator store — generated by create-api-home" >/dev/null
fi

cd "$DEPLOY"
git init -q -b main
git add -A
git -c user.email=deploy@local -c user.name=create-api-home commit -q -m "deploy store $(date +%Y-%m-%d-%H%M)"
# on a host (Render etc.) there is no `gh` credential helper — push with the
# GH_TOKEN/GITHUB_TOKEN env if present; locally fall back to gh's helper.
TOK="${GH_TOKEN:-$GITHUB_TOKEN}"
if [ -n "$TOK" ]; then REMOTE="https://x-access-token:${TOK}@github.com/$OWNER/$REPO.git"; else REMOTE="https://github.com/$OWNER/$REPO.git"; fi
git remote add origin "$REMOTE" 2>/dev/null || git remote set-url origin "$REMOTE"
git push -q -f origin main

echo "▶ enabling GitHub Pages (main / root)"
gh api -X POST "repos/$OWNER/$REPO/pages" -f 'source[branch]=main' -f 'source[path]=/' >/dev/null 2>&1 \
  || gh api -X PUT "repos/$OWNER/$REPO/pages" -f 'source[branch]=main' -f 'source[path]=/' >/dev/null 2>&1 || true

URL="$(gh api "repos/$OWNER/$REPO/pages" --jq '.html_url' 2>/dev/null || echo "https://$OWNER.github.io/$REPO/")"
echo "✓ deployed. live URL → $URL"
